import java.util.Random;
import java.util.Scanner;
   
public class NumberGame
{

    public static void main(String[] args)
    {
        int iAns, iGuess, iChance = 5;
        int iRound = 3;
        int iVar = 1;
        int iScore = 0;
        final int Max = 50;

        System.out.println("----WELCOME TO GUESS THE NUMBER GAME----");
        System.out.println("-----HOW TO PLAY-------");
        System.out.println("You have to guess the number generated by the computer.\n If you win the game stops\n");
        System.out.println("-----RULES OF GAME-----");
        System.out.println("1.Toatal Rounds will be 3");
        System.out.println("2.Each Round will have 5 chances to guess the number correct");
        System.out.println("3.You are not allowed to enter a number greater than 50");
        System.out.println("\n\nStart Playing!!!\n\n");
  do
  {
    System.out.println("--------------------------------------------------");
    System.out.println("Rounds Remaining: "+iRound);
    System.out.println("--------------------------------------------------");
    System.out.println("--------------------------------------------------");
    System.out.println("Chances Remaining to Guess: "+iChance);
    System.out.println("--------------------------------------------------");

        Scanner keyboard = new Scanner(System.in);
        Random rand = new Random();
        
        iAns = rand.nextInt(Max) + 1;

        System.out.println("\nPlease Guess the number between 1 to 50");
        iGuess =keyboard.nextInt();
         
        if(iGuess > 50)
        {
            System.out.println("Invalid Input");
            System.out.println("Kindly enter the number between 1-50\n");
        }
        if(iGuess == iAns)
        {
            System.out.println("Hurrah!!You Won");
            System.out.println("The number was "+iAns);
            iVar = 0;
        }

        else if((iGuess < 50) && (iGuess < iAns))
        {
            System.out.println("System says: Try a smaller number");
            System.out.println("Oops! Sorry, but the number was "+iAns);
        }

        else if((iGuess < 50) && (iGuess > iAns))
        {
            System.out.println("\nSystem says: Try a greater number");
            System.out.println("Oops! Sorry, but the number was "+iAns+"\n");  
        }

        if(iGuess < 50)
        {
        iChance--;
        }

        if(iChance == 0)
        {
            iRound--;
           iChance = 5;    
           
        }
    
        
    }while((iRound != 0) && (iVar == 1) );

    if((iRound == 0) && (iGuess != iAns))
    {
    System.out.println("\nSorry, no chances left");
    System.out.println("Better Luck next time!");
    }
    
    System.out.println("Thank you for using our game");
}
}
